spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
    level:
      root: ${LOG-LEVEL}
